### ISSUE TITLE
vue组件找不到HomeHeader文件夹好像工程里面没有

### ISSUE THREAD

**Issue by 404name** [lvr1997/kd-shop#9]

**Comment by lvr1997** [comment]
您好，更新下最新代码。仓库地址：https://gitee.com/kd-shop/kd-shop.git


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lvr1997/kd-shop"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月4日(星期四) 中午11:46
收件人:&nbsp;"lvr1997/kd-shop"<kd-shop@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[lvr1997/kd-shop] vue组件找不到HomeHeader文件夹好像工程里面没有 (#9)

**Comment by 404name** [comment]
好的，谢谢啦，太及时了，哈哈~

**Comment by 404name** [comment]
麻烦再问一下，gitee版本web默认进入后台，然后前台路由/home都是直接跳到404，是怎么回事0.0，而且我也不知道前台路由了

**Comment by lvr1997** [comment]
刚刚有点事在忙，没有来得及回复。
科大商铺 的前端：前台门户和后台管理是分离出来的。前台项目kd-shop-student，后台管理项目kd-shop-web


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lvr1997/kd-shop"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月4日(星期四) 中午1:06
收件人:&nbsp;"lvr1997/kd-shop"<kd-shop@noreply.github.com&gt;;
抄送:&nbsp;"西瓜是咸的 (^o^)/"<lvr1997@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [lvr1997/kd-shop] vue组件找不到HomeHeader文件夹好像工程里面没有 (#9)





 
麻烦再问一下，gitee版本web默认进入后台，然后前台路由/home都是直接跳到404，是怎么回事0.0，而且我也不知道前台路由了
